use customer_behaviour;

-- total revenue generated by females and males--

select gender, SUM(purchase_amount) as total_revenue
from customer 
group by gender;

-- customer used discount but still spent more than Averange amount --

select customer_id, purchase_amount from customer
where discount_applied = "Yes" and purchase_amount >=
(select avg(purchase_amount) from customer);

-- Top 5 product with highest review rating --

select item_purchased, avg(review_rating) as Avg_Product_rating from customer
group by item_purchased
order by avg(review_rating) desc limit 5;

-- compare average purchase amount between standard and Express shippinng --

select shipping_type, avg(purchase_amount) from customer
where shipping_type in ("standard","Express")
group by shipping_type;

-- compare average spend and total revenue between subscribers and non-subscribers --

select subscription_status, count(customer_id) as total_customers, 
avg(purchase_amount) as avg_spend, sum(purchase_amount) as total_revenue from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- which 5 products have highest percentage of purchase amount with discount applied --

select item_purchased,
(100* sum(case when discount_applied = "Yes" then 1 else 0 end)/count(*)) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- segment customers into new, returning, and loyal based on their total --
-- number of previous purchases, and show the count of each segment. --

with customer_type as(
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then "New"
    when previous_purchases between 2 and 10 then "returning"
    else "loyal"
    end as customer_segment
from customer
)
select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment;

-- what are the top 3 most purchased products within each category --

with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;

-- Are customer who are repeat buyers(more than 5 previous purchases) also like to subscribers --

select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- revenue contribution of each age group --

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;